RESERVATION_STATUS_REQUESTED = "requested"
RESERVATION_STATUS_CONFIRMED = "confirmed"
RESERVATION_STATUS_CANCELLED = "cancelled"
RESERVATION_STATUS_ON_HOLD = "on_hold"

RESERVATION_STATUS_CHOICES = (
    (RESERVATION_STATUS_REQUESTED, "Requested"),
    (RESERVATION_STATUS_CONFIRMED, "Confirmed"),
    (RESERVATION_STATUS_CANCELLED, "Cancelled"),
    (RESERVATION_STATUS_ON_HOLD, "On Hold"),
)
